const String AUTH_NOT_DETERMINED = 'AUTH_NOT_DETERMINED';
const String AUTH_IN_PROGRESS = "AUTH_IN_PROGRESS";
const String AUTH_FAILED = "AUTH_FAILED";
const String AUTH_SUCCEEDED = "AUTH_SUCCEEDED";
